name: Greet Person Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the name
        run: echo "Hello, ${{ github.event.inputs.name }}!"